#!/bin/bash

docker buildx create --name multiarch --driver docker-container --platform linux/amd64,linux/arm64 --use
docker buildx build --push --platform linux/arm/v7,linux/arm64/v8,linux/amd64 --tag nitiknirdorg/tester:latest .
