#!/bin/bash

docker run --privileged --rm tonistiigi/binfmt --install all
docker run --privileged --rm multiarch/qemu-user-static --reset -p yes
docker buildx create --name multiarch --driver docker-container --platform linux/amd64,linux/arm64/v8 --use
docker buildx build --tag $IMAGE_NAME --file ${DOCKERFILE_PATH} --progress=plain --push --platform linux/amd64,linux/arm64/v8 .
