#!/bin/bash
docker run --privileged --rm tonistiigi/binfmt --install all
docker run --privileged --rm multiarch/qemu-user-static --reset -p yes
docker buildx rm builder
docker buildx rm multiarch
docker buildx create --name multiarch --driver docker-container --platform linux/amd64,linux/arm64 --use
